name: Increment version TEST

on: 
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install bump2version
        run: >-
          python -m
          pip install
          --upgrade
          bump2version
      - name: Configure Git
        run: >-
          git config --global user.email "gshel@users.noreply.github.com" &&
          git config --global user.name "Github Actions"
      - name: Increment VERSION
        run: >-
          bump2version --current-version `cat VERSION` 
          `echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | grep -Eo "major|minor|patch"` 
          VERSION && 
          `cat VERSION`
      - name: Push Changes to Branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

