name: Version Bump and Publish to PyPi

on:
  push:
    branches:
      - master

jobs:
  version_bump_n_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Output commit_msg.PR_NUMBER
        id: commit_msg
        run: |
          echo "::set-output name=PR_NUMBER::$(echo ${{ toJson(github.event.head_commit.message) }} | sed -r 's;.*\#([0-9]{1,}).*;\1;')"
      - name: Output pr.LABELS
        id: pr
        run: >-
          echo "::set-output name=LABELS::`curl -sH 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/${{ github.event.repository.full_name }}/pulls/${{ steps.commit_msg.outputs.PR_NUMBER }} |
          jq -c [.labels[].name]`"
      - name: Output increment.Type
        id: increment
        run: |
          echo "::set-output name=TYPE::`echo '${{ steps.pr.outputs.labels }}' | grep -Eo 'major|minor|patch'`"
      - name: Set up Python
        if: ${{ steps.increment.outputs.TYPE }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install bump2version
        if: ${{ steps.increment.outputs.TYPE }}
        run: |
          python -m pip install --upgrade bump2version
      - name: Configure Git
        if: ${{ steps.increment.outputs.TYPE }}
        run: |
          git config --global user.email "${{ github.event.sender.login }}@users.noreply.github.com"
          git config --global user.name "Github Actions"
      - name: Increment semrush/__init__.py
        if: ${{ steps.increment.outputs.TYPE }}
        run: |
          echo "`python3.8 semrush/__init__.py`"
          bump2version --current-version `python semrush/__init__.py` ${{ steps.increment.outputs.TYPE }} semrush/__init__.py
          echo "${{ steps.increment.outputs.TYPE }} bump to: `python semrush/__init__.py`"
      - name: Push Changes to Branch
        if: ${{ steps.increment.outputs.TYPE }}
        run: |
          git checkout ${GITHUB_REF##*/}
          git add semrush/__init__.py
          git push
      - name: Install pypa/build
        if: ${{ steps.increment.outputs.TYPE }}
        run: |
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        if: ${{ steps.increment.outputs.TYPE }}
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to Test PyPI
        if: ${{ steps.increment.outputs.TYPE }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: ${{ steps.increment.outputs.TYPE }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
